# Dependencies
markdown:         kramdown
mathjax:          true
highlighter:      rouge

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            MBNpy
tagline:          'mbnpy'
description:      'Scalable Baeysian network for complex systems'
domain:           jieunbyun.github.io/MBNpy
url:              "https://jieunbyun.github.io"
baseurl:          "/MBNpy"

author:
  name:           'Ji-Eun Byun'

#paginate:         5

# Paginate for jekyll v3.0
pagination:
  enabled: true
  debug: false
  collections: 'posts'
  per_page: 5
  permalink: '/page/:num/'

# Plugins
plugins: 
  - jekyll-paginate-v2
  - jekyll-gist

#plugins_dir:
  #_plugins

# Navigation Links
nav:
  - title: "Home"
    url: "/"
  - title: "Documentation"
    url: "/MBNpy/docs/sphinx/build/html/index.html"

include:
  - sphinx/build/html
  - sphinx/source/_static

include:
  - sphinx/build/html

defaults:
  - scope:
      path: "sphinx/build/html"
    values:
      baseurl: "/MBNpy/docs/sphinx"



